import Link from "next/link";
import { getRandomHistoryFacts,getDefaultFacts } from "./data";
import { SamuraiScroll } from "../utils/scroll";
/*


   secondary goal is to connect the componenets in such a wahy which genarate a greate user experience
   so that the user feels immersed in the experience of learning history


*/ 
export default async function FreedomScrollPage() {
  //const { facts, error } = await getRandomHistoryFacts();
  const facts= getDefaultFacts();
  const error=null;
  
  return (
    <main className="min-h-screen bg-black">
      {/* Header */}
      <header className="flex justify-between bg-zinc-900/50 backdrop-blur-sm shadow-sm sticky top-0 z-20 border-b border-zinc-800">
         <Link href="/" className="text-gray-400 hover:text-white flex items-center gap-2 font-medium p-4 transition-colors">
            ← Back to Home
          </Link>
        <div className="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
          <h1 className="text-3xl font-bold text-gray-100 flex items-center gap-2 justify-center">
            <span className="text-4xl">📜</span> Freedom Scroll
          </h1>
        </div>
        <div className="w-24"></div> 
      </header>

      {/* Content Area */}
      <div className="max-w-7xl mx-auto px-4 py-12 flex flex-col items-center justify-center min-h-[80vh]">
        
       
            
            {error && (
              <div className="text-red-800 font-bold p-4 border border-red-800/20 bg-red-50/50 rounded text-center">
                <p>The archives are temporarily closed.</p>
                <p className="text-sm mt-2 text-red-700">{error}</p>
              </div>
            )}

            {!error && facts && (
              <div className="flex justify-center text-left h-screen w-screen flex-col">
                <div className="flex text-center border-b-2 border-amber-900/20 pb-2 mb-4 px-1.5">
                  <p className="text-amber-800/70 mt-0.5 font-serif italic mx-2">
                    era={facts[0]?.era || "Ancient Records"}
                  </p>
                </div>
              <div className="flex justify-center">
                {facts.map((fact, index) => (
                   <SamuraiScroll 
                    fact={fact}
                    index={index}
                    width="max-w-4xl">
                    </SamuraiScroll>
                ))}
              </div>

                <div className="pt-6 text-center">
                  <p className="text-amber-100/40 font-serif italic text-xs">
                    ~ Generated by The India Facts Portal ~
                  </p>
                </div>
              </div>
            )}

       

      </div>
    </main>
  );
}